python train.py --experiment_dir=exp \
                --experiment_id=0 \
                --batch_size=16 \
                --lr=0.001 \
                --epoch=100 \
                --sample_steps=50 \
                --schedule=20 \
                --L1_penalty=100 \
                --Lconst_penalty=15 \
